name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 6,18 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_token: ${{ github.token }}
          committer_message: "chore: update metrics [skip ci]"
          optimize: css, xml
          config_timezone: Europe/London
          base: header, activity, repositories, metadata
          base_indepth: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_calendar: yes

  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: header.svg
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_token: ${{ github.token }}
          committer_message: "chore: update metrics [skip ci]"
          optimize: css, xml
          config_timezone: Europe/London
          base: header
          base_indepth: yes

  achievements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          committer_token: ${{ github.token }}
          committer_message: "chore: update metrics [skip ci]"
          optimize: css, xml
          config_timezone: Europe/London
          plugin_achievements: yes
